server:
    port: 8000
    servlet:
        context-path: /

spring:
    application:
        name: BaiDuAI

    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB


my:
    #百度文字识别api相关参数
    character:
        #url
        url: https://aip.baidubce.com/rest/2.0/ocr/v1/general


        #获取token相关参数
        key: scwFcovWUYHXuEwsFkXabd8j
        secret: mefn5MA7kB8roVv800yrmdbM6F1mwNDk

